---
openapi: 3.0.1
info:
  title: WeatherVain Backend API V1
  version: v1
paths:
  "/api/v1/addresses":
    post:
      summary: Query for Addresses
      tags:
      - Addresses
      parameters: []
      responses:
        '200':
          description: successful
        '400':
          description: bad query
        '500':
          description: internal service error
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/address_search_query"
  "/api/v1/forecasts":
    post:
      summary: request forecast
      tags:
      - Forecasts
      parameters: []
      responses:
        '200':
          description: successful
        '400':
          description: Bad or Missing Zip Code
        '404':
          description: Address / Weather Forecast not found!
        '500':
          description: some kind of internal error
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/forecast_query"
servers:
- url: https://weather-vain.onrender.com/
  description: Weather Service
components:
  schemas:
    address:
      type: object
      properties:
        street_address:
          type: string
        city:
          type: string
        country:
          type: string
        state:
          type: string
        zip_code:
          type: string
    address_search_query:
      type: object
      properties:
        query:
          type: string
    address_search_resp:
      type: object
      properties:
        address_matches:
          type: array
          items:
            "$ref": "#/components/schemas/address"
    forecast_query:
      type: object
      properties:
        address:
          "$ref": "#/components/schemas/address"
    forecast_resp:
      type: object
      properties:
        address_matches:
          type: array
          items:
            "$ref": "#/components/schemas/forecast_item"
    forecast_item:
      type: object
      properties:
        start_time:
          type: string
        end_time:
          type: string
        temperature_low:
          type: integer
        temperature_high:
          type: integer
        precipitation:
          type: string
        skies:
          type: string
